"""
Lead Persona model - stores LLM-generated detailed lead personas for hyper-personalization.
"""
from django.db import models
from django.utils import timezone


class LeadPersona(models.Model):
    """
    A detailed digital twin of a lead, generated by an LLM based on profile data and company context.
    
    Contains predicted pain points, goals, messaging preferences, and buy signals
    that are used by the follow-up agent to craft hyper-personalized outreach.
    """
    lead = models.ForeignKey('Lead', on_delete=models.CASCADE, related_name='personas')
    campaign = models.ForeignKey('core.Campaign', on_delete=models.CASCADE)
    
    # Persona fields (stored as JSON for flexibility)
    pain_points = models.JSONField(default=list)  # List of predicted pain points
    goals = models.JSONField(default=list)  # List of professional goals
    messaging_preferences = models.JSONField(default=dict)  # {tone, formality, topics, style}
    buy_signals = models.JSONField(default=list)  # List of {signal_type, strength, source, description}
    confidence_score = models.FloatField(default=0.5)  # LLM confidence in persona (0-1)
    recommendations = models.JSONField(default=list)  # Specific outreach suggestions
    
    # Metadata
    generated_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    version = models.PositiveIntegerField(default=1)
    
    class Meta:
        unique_together = ('lead', 'campaign')
        indexes = [
            models.Index(fields=['lead', 'campaign'], name='persona_lead_campaign_idx'),
            models.Index(fields=['confidence_score'], name='persona_confidence_idx'),
            models.Index(fields=['generated_at'], name='persona_generated_idx'),
        ]
        verbose_name = "Lead Persona"
        verbose_name_plural = "Lead Personas"
    
    def __str__(self):
        return f"Persona v{self.version} for {self.lead.public_identifier}"
    
    @property
    def is_high_confidence(self) -> bool:
        """Check if the persona has high confidence (>= 0.7)."""
        return self.confidence_score >= 0.7
    
    @property
    def has_buy_signals(self) -> bool:
        """Check if any buy signals were identified."""
        return len(self.buy_signals) > 0
    
    def get_formatted_pain_points(self, limit: int = 3) -> list[str]:
        """Get formatted pain points, optionally limited to a number."""
        return self.pain_points[:limit] if self.pain_points else []
    
    def get_formatted_goals(self, limit: int = 3) -> list[str]:
        """Get formatted goals, optionally limited to a number."""
        return self.goals[:limit] if self.goals else []
    
    def get_formatted_buy_signals(self, limit: int = 3) -> list[str]:
        """Get formatted buy signals descriptions, optionally limited to a number."""
        return [s.get('description', 'Unknown') for s in self.buy_signals[:limit]] if self.buy_signals else []