"""
Lead Persona model - stores LLM-generated detailed lead personas for hyper-personalization.
"""

from django.db import models
from django.utils import timezone


class LeadPersona(models.Model):
    """
    A detailed digital twin of a lead, generated by an LLM based on profile data and company context.

    Contains predicted pain points, goals, messaging preferences, and buy signals
    that are used by the follow-up agent to craft hyper-personalized outreach.
    """

    lead: models.ForeignKey = models.ForeignKey("Lead", on_delete=models.CASCADE, related_name="personas")  # type: ignore[var-annotated,assignment]
    campaign: models.ForeignKey = models.ForeignKey("core.Campaign", on_delete=models.CASCADE)  # type: ignore[var-annotated,assignment]

    # Persona fields (stored as JSON for flexibility)
    pain_points: models.JSONField = models.JSONField(
        default=list
    )  # List of predicted pain points  # type: ignore[var-annotated]
    goals: models.JSONField = models.JSONField(
        default=list
    )  # List of professional goals  # type: ignore[var-annotated]
    messaging_preferences: models.JSONField = models.JSONField(
        default=dict
    )  # {tone, formality, topics, style}  # type: ignore[var-annotated]
    buy_signals: models.JSONField = models.JSONField(
        default=list
    )  # List of {signal_type, strength, source, description}  # type: ignore[var-annotated]
    confidence_score: models.FloatField = models.FloatField(
        default=0.5
    )  # LLM confidence in persona (0-1)  # type: ignore[var-annotated]
    recommendations: models.JSONField = models.JSONField(
        default=list
    )  # Specific outreach suggestions  # type: ignore[var-annotated]

    # Metadata
    generated_at: models.DateTimeField = models.DateTimeField(auto_now_add=True)  # type: ignore[var-annotated]
    last_updated: models.DateTimeField = models.DateTimeField(auto_now=True)  # type: ignore[var-annotated]
    version: models.PositiveIntegerField = models.PositiveIntegerField(default=1)  # type: ignore[var-annotated]

    class Meta:
        unique_together = ("lead", "campaign")
        indexes = [
            models.Index(fields=["lead", "campaign"], name="persona_lead_campaign_idx"),
            models.Index(fields=["confidence_score"], name="persona_confidence_idx"),
            models.Index(fields=["generated_at"], name="persona_generated_idx"),
        ]
        verbose_name = "Lead Persona"
        verbose_name_plural = "Lead Personas"

    def __str__(self) -> str:
        return f"Persona v{self.version} for {self.lead.public_identifier}"

    @property
    def is_high_confidence(self) -> bool:
        """Check if the persona has high confidence (>= 0.7)."""
        return self.confidence_score >= 0.7

    @property
    def has_buy_signals(self) -> bool:
        """Check if any buy signals were identified."""
        return len(self.buy_signals) > 0

    def get_formatted_pain_points(self, limit: int = 3) -> list[str]:
        """Get formatted pain points, optionally limited to a number."""
        return self.pain_points[:limit] if self.pain_points else []

    def get_formatted_goals(self, limit: int = 3) -> list[str]:
        """Get formatted goals, optionally limited to a number."""
        return self.goals[:limit] if self.goals else []

    def get_formatted_buy_signals(self, limit: int = 3) -> list[str]:
        """Get formatted buy signals descriptions, optionally limited to a number."""
        return (
            [s.get("description", "Unknown") for s in self.buy_signals[:limit]]
            if self.buy_signals
            else []
        )
