# Generated by Django 5.2.15 on 2026-06-28 22:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0010_campaigntemplate_delete_customuser"),
        ("crm", "0019_lead_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("campaign_started", "Campaign Started"),
                            ("campaign_paused", "Campaign Paused"),
                            ("campaign_completed", "Campaign Completed"),
                            ("rate_limit_warning", "Rate Limit Warning"),
                            ("new_message", "New Message"),
                            ("campaign_error", "Campaign Error"),
                            ("system_announcement", "System Announcement"),
                        ],
                        help_text="Type of notification",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=255),
                ),
                ("message", models.TextField(help_text="Notification message content")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether notification has been read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was read", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional JSON data for the notification",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When notification was created",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related campaign (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.campaign",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related deal (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.deal",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who receives the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="notificatio_created_ae6ed6_idx"
                    ),
                ],
            },
        ),
    ]
