# Generated by Django 5.2.15 on 2026-06-14 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_cooldown_minutes_campaign_is_paused_and_more'),
        ('crm', '0013_alter_deal_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_points', models.JSONField(default=list)),
                ('goals', models.JSONField(default=list)),
                ('messaging_preferences', models.JSONField(default=dict)),
                ('buy_signals', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('recommendations', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead Persona',
                'verbose_name_plural': 'Lead Personas',
                'indexes': [models.Index(fields=['lead', 'campaign'], name='persona_lead_campaign_idx'), models.Index(fields=['confidence_score'], name='persona_confidence_idx'), models.Index(fields=['generated_at'], name='persona_generated_idx')],
                'unique_together': {('lead', 'campaign')},
            },
        ),
    ]
