# Generated by Django 5.2.15 on 2026-06-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_cooldown_minutes_campaign_is_paused_and_more'),
        ('crm', '0015_message_note'),
        ('linkedin', '0014_add_smart_rate_limiting_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Link Click',
                'verbose_name_plural': 'Link Clicks',
            },
        ),
        migrations.CreateModel(
            name='LinkedInCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_encrypted', models.BinaryField(help_text='Encrypted LinkedIn email', max_length=500)),
                ('password_encrypted', models.BinaryField(help_text='Encrypted LinkedIn password', max_length=500)),
                ('username', models.CharField(blank=True, help_text='Display name/username for this credential', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invalid', 'Invalid - needs re-verification'), ('expired', 'Expired - needs rotation'), ('locked', 'Locked - temporarily disabled'), ('backup', 'Backup credential')], default='active', help_text='Credential status and validity', max_length=20)),
                ('last_verified', models.DateTimeField(blank=True, help_text='When credentials were last verified', null=True)),
                ('verification_failed_at', models.DateTimeField(blank=True, help_text='When last verification failed', null=True)),
                ('verification_failures', models.PositiveIntegerField(default=0, help_text='Number of consecutive verification failures')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Total number of actions performed with these credentials')),
                ('last_used', models.DateTimeField(blank=True, help_text='When these credentials were last used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When these credentials expire (for rotation)', null=True)),
                ('rotated_at', models.DateTimeField(blank=True, help_text='When these credentials were last rotated', null=True)),
                ('rotation_required_days', models.PositiveIntegerField(default=90, help_text='Days after which credentials should be rotated')),
                ('is_primary', models.BooleanField(default=True, help_text='Whether this is the primary credential for the profile')),
                ('is_backup', models.BooleanField(default=False, help_text='Whether this is a backup credential')),
                ('security_alert_sent_at', models.DateTimeField(blank=True, help_text='When last security alert was sent', null=True)),
                ('backup_of', models.ForeignKey(blank=True, help_text='Original credential this is backed up from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_credentials', to='crm.linkedincredentials')),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign using these credentials', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkedin_credentials', to='core.campaign')),
                ('linkedin_profile', models.OneToOneField(blank=True, help_text='The LinkedIn profile this credential belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='linkedin.linkedinprofile')),
            ],
            options={
                'verbose_name': 'LinkedIn Credential',
                'verbose_name_plural': 'LinkedIn Credentials',
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkedInCredentialLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verified', 'Verified'), ('failed', 'Failed'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('rotated', 'Rotated'), ('backup', 'Backup Created'), ('usage', 'Usage Recorded')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.linkedincredentials')),
            ],
            options={
                'verbose_name': 'LinkedIn Credential Log',
                'verbose_name_plural': 'LinkedIn Credential Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='Original destination URL', max_length=1000)),
                ('short_code', models.CharField(help_text='Short unique identifier for the link', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is active')),
                ('utm_source', models.CharField(blank=True, help_text='UTM source parameter', max_length=100)),
                ('utm_medium', models.CharField(blank=True, help_text='UTM medium parameter', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, help_text='UTM campaign parameter', max_length=100)),
                ('utm_term', models.CharField(blank=True, help_text='UTM term parameter', max_length=100)),
                ('utm_content', models.CharField(blank=True, help_text='UTM content parameter', max_length=100)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_user_agent', models.CharField(blank=True, max_length=500)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_links', to='core.campaign')),
            ],
            options={
                'verbose_name': 'Tracked Link',
                'verbose_name_plural': 'Tracked Links',
            },
        ),
        migrations.CreateModel(
            name='LinkDealConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('click', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.linkclick')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_conversions', to='crm.deal')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_links', to='crm.trackedlink')),
            ],
            options={
                'verbose_name': 'Link Conversion',
                'verbose_name_plural': 'Link Conversions',
            },
        ),
        migrations.AddField(
            model_name='linkclick',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='crm.trackedlink'),
        ),
        migrations.AddIndex(
            model_name='linkedincredentials',
            index=models.Index(fields=['status', 'expires_at'], name='crm_linkedi_status_f7114e_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedincredentials',
            index=models.Index(fields=['campaign', 'status'], name='crm_linkedi_campaig_fdc633_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedincredentiallog',
            index=models.Index(fields=['credentials', 'created_at'], name='crm_linkedi_credent_088868_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['short_code'], name='trackedlink_shortcode_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['campaign'], name='trackedlink_campaign_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['created_at'], name='trackedlink_created_idx'),
        ),
        migrations.AddIndex(
            model_name='linkdealconversion',
            index=models.Index(fields=['link'], name='linkconv_link_idx'),
        ),
        migrations.AddIndex(
            model_name='linkdealconversion',
            index=models.Index(fields=['deal'], name='linkconv_deal_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['link', 'clicked_at'], name='linkclick_link_time_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['ip_address'], name='linkclick_ip_idx'),
        ),
    ]
