# Generated by Django 5.2.15 on 2026-06-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_linkclick_linkedincredentials_linkedincredentiallog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedincredentials',
            name='status',
            field=models.CharField(choices=[('stored', 'Stored - not yet verified'), ('tested', 'Tested - login attempted'), ('active', 'Active - verified and working'), ('invalid', 'Invalid - verification failed'), ('expired', 'Expired - needs rotation'), ('locked', 'Locked - checkpoint/challenge detected'), ('backup', 'Backup credential')], default='active', help_text='Credential status and validity', max_length=20),
        ),
    ]
