# Generated by Django 5.2.15 on 2026-06-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0017_update_linkedin_credentials_verification_status"),
        ("emails", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="mailbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="emails.mailbox",
            ),
        ),
    ]
