# Generated by Django 5.2.15 on 2026-06-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0018_deal_email_sent_at_deal_mailbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Notes about this lead", null=True
            ),
        ),
    ]
