# Generated by Django 5.2.15 on 2026-07-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0019_lead_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="deals", to="crm.lead"
            ),
        ),
    ]
