# Generated by Django 5.2.15 on 2026-06-14 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_cooldown_minutes_campaign_is_paused_and_more'),
        ('linkedin', '0011_ghost_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_profiles', to='core.campaign'),
        ),
        migrations.CreateModel(
            name='RecoveryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('reduce_velocity', 'Reduce velocity'), ('add_cooldown', 'Add cooldown period'), ('switch_message', 'Switch message variant'), ('pause', 'Pause campaign'), ('switch_account', 'Switch LinkedIn account')], max_length=20)),
                ('before_state', models.JSONField(default=dict)),
                ('after_state', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('execution_result', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
            ],
            options={
                'verbose_name_plural': 'Recovery actions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('connections_sent', models.PositiveIntegerField(default=0)),
                ('connections_accepted', models.PositiveIntegerField(default=0)),
                ('connection_accept_rate', models.FloatField(default=0.0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('messages_replied', models.PositiveIntegerField(default=0)),
                ('response_rate', models.FloatField(default=0.0)),
                ('errors_total', models.PositiveIntegerField(default=0)),
                ('rate_limit_errors', models.PositiveIntegerField(default=0)),
                ('auth_errors', models.PositiveIntegerField(default=0)),
                ('network_errors', models.PositiveIntegerField(default=0)),
                ('deals_created', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('detectability_score', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign health metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['campaign', 'timestamp'], name='linkedin_ca_campaig_27d9ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('connection_rate', 'Connection accept rate too low'), ('response_rate', 'Response rate too low'), ('rate_limit', 'Rate limit warnings'), ('auth_error', 'Authentication errors'), ('detection', 'LinkedIn detectability high'), ('error_spike', 'Error rate spike')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('auto_remediation_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
            ],
            options={
                'verbose_name_plural': 'Health alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'is_resolved'], name='linkedin_he_campaig_37f7e4_idx')],
            },
        ),
    ]
