# Generated by Django 5.2.15 on 2026-06-14 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_cooldown_minutes_campaign_is_paused_and_more'),
        ('crm', '0013_alter_deal_state'),
        ('linkedin', '0012_linkedinprofile_campaign_recoveryaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStateGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('graph_data', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state_graph', to='core.campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign state graphs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('start', 'Start'), ('wait', 'Wait/Delay'), ('message', 'Send Message'), ('gate', 'Qualification Gate'), ('decision', 'Decision'), ('branch', 'Branch'), ('webhook', 'Webhook'), ('end', 'End')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='linkedin.campaignstategraph')),
            ],
            options={
                'verbose_name': 'State node',
                'verbose_name_plural': 'State nodes',
                'ordering': ['state_graph', 'x', 'y'],
            },
        ),
        migrations.CreateModel(
            name='CampaignState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_nodes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('error', 'Error')], default='active', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('wait_until', models.DateTimeField(blank=True, null=True)),
                ('wait_reason', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_machines', to='crm.deal')),
                ('state_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkedin.campaignstategraph')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkedin.statenode')),
            ],
            options={
                'verbose_name_plural': 'Campaign states',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(default='always', max_length=50)),
                ('condition_config', models.JSONField(default=dict)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='linkedin.statenode')),
                ('state_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='linkedin.campaignstategraph')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='linkedin.statenode')),
            ],
            options={
                'verbose_name': 'State transition',
                'verbose_name_plural': 'State transitions',
                'ordering': ['state_graph', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CampaignExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='linkedin.campaignstate')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkedin.statenode')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkedin.statetransition')),
            ],
            options={
                'verbose_name_plural': 'Campaign execution logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='campaignstate',
            index=models.Index(fields=['deal', 'status'], name='linkedin_ca_deal_id_678430_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignstate',
            index=models.Index(fields=['state_graph', 'status'], name='linkedin_ca_state_g_037878_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignexecutionlog',
            index=models.Index(fields=['state_machine', 'timestamp'], name='linkedin_ca_state_m_fa4f8b_idx'),
        ),
    ]
