# Generated by Django 5.2.15 on 2026-06-14 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0013_state_machine_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=20)),
                ('limit_type', models.CharField(max_length=20)),
                ('limit_exceeded', models.PositiveIntegerField()),
                ('actual_count', models.PositiveIntegerField()),
                ('warning_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('at_time', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('linkedin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_warnings', to='linkedin.linkedinprofile')),
            ],
            options={
                'ordering': ['-at_time'],
            },
        ),
        migrations.CreateModel(
            name='SmartRateLimitContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day_limit_multiplier', models.FloatField(default=1.0)),
                ('day_of_week_limit_multiplier', models.FloatField(default=1.0)),
                ('detectability_score', models.PositiveIntegerField(default=50)),
                ('last_detectability_update', models.DateTimeField(auto_now=True)),
                ('last_action_type', models.CharField(blank=True, max_length=20)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_actions', models.PositiveIntegerField(default=0)),
                ('action_streak_reset_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_context', to='linkedin.linkedinprofile')),
            ],
            options={
                'verbose_name_plural': 'Smart rate limit contexts',
            },
        ),
    ]
