# Generated by Django 5.2.15 on 2026-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_siteconfig_bettercontact_api_key_and_more"),
        ("linkedin", "0014_add_smart_rate_limiting_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name="actionlog",
            index=models.Index(
                fields=["status", "created_at"], name="linkedin_ac_status_bfdaec_idx"
            ),
        ),
    ]
