# Generated by Django 5.2.15 on 2026-06-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0015_actionlog_error_message_actionlog_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statenode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("start", "Start"),
                    ("wait", "Wait/Delay"),
                    ("message", "Send Message"),
                    ("gate", "Qualification Gate"),
                    ("decision", "Decision"),
                    ("branch", "Branch"),
                    ("webhook", "Webhook"),
                    ("link", "Insert Tracked Link"),
                    ("end", "End"),
                ],
                max_length=20,
            ),
        ),
    ]
