# Generated by Django 5.2.15 on 2026-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0016_alter_statenode_node_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="duration_ms",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
