# Generated by Django 5.2.15 on 2026-07-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0018_merge_0002_encrypt_cookie_data_0017_actionlog_duration_ms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("connect", "Connect"),
                    ("check_pending", "Check Pending"),
                    ("follow_up", "Follow Up"),
                    ("send_manual_message", "Send Manual Message"),
                ],
                max_length=20,
            ),
        ),
    ]
