# Generated by Django 5.2.15 on 2026-07-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0019_add_action_log_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("connect", "Connect"),
                    ("check_pending", "Check Pending"),
                    ("follow_up", "Follow Up"),
                    ("send_manual_message", "Send Manual Message"),
                    ("campaign_paused", "Campaign Paused"),
                    ("campaign_started", "Campaign Started"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="linkedin_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_logs",
                to="linkedin.linkedinprofile",
            ),
        ),
    ]
