# Type stubs for Django models
from typing import Any, TypeVar, Generic, overload

_T = TypeVar("_T")

class Manager(Generic[_T]):
    def all(self) -> Any: ...
    def filter(self, *args, **kwargs) -> Any: ...
    def exclude(self, *args, **kwargs) -> Any: ...
    def get(self, *args, **kwargs) -> Any: ...
    def create(self, **kwargs: Any) -> Any: ...
    def update(self, **kwargs: Any) -> int: ...
    def delete(self) -> tuple[int, dict[str, int]]: ...
    def count(self) -> int: ...
    def first(self) -> Any | None: ...
    def last(self) -> Any | None: ...
    def exists(self) -> bool: ...
    def order_by(self, *field_names: str) -> Any: ...
    def reverse(self) -> Any: ...
    def distinct(self, *field_names: str) -> Any: ...

class QuerySet(Generic[_T]):
    def all(self) -> "QuerySet[_T]": ...
    def filter(self, *args, **kwargs) -> "QuerySet[_T]": ...
    def exclude(self, *args, **kwargs) -> "QuerySet[_T]": ...
    def get(self, *args, **kwargs) -> _T: ...
    def create(self, **kwargs: Any) -> _T: ...
    def update(self, **kwargs: Any) -> int: ...
    def delete(self) -> tuple[int, dict[str, int]]: ...
    def count(self) -> int: ...
    def first(self) -> _T | None: ...
    def last(self) -> _T | None: ...
    def exists(self) -> bool: ...
    def order_by(self, *field_names: str) -> "QuerySet[_T]": ...
    def reverse(self) -> "QuerySet[_T]": ...
    def distinct(self, *field_names: str) -> "QuerySet[_T]": ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...

class ForeignKey(Generic[_T]):
    def __get__(self, obj: Any, objtype: Any | None = None) -> _T: ...
    def __set__(self, obj: Any, value: _T | None) -> None: ...

class OneToOneField(Generic[_T]):
    def __get__(self, obj: Any, objtype: Any | None = None) -> _T: ...
    def __set__(self, obj: Any, value: _T | None) -> None: ...

class ManyToManyField(Generic[_T]):
    def __get__(self, obj: Any, objtype: Any | None = None) -> Manager[_T]: ...
    def __set__(self, obj: Any, value: Any) -> None: ...

class TextField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> str: ...
    def __set__(self, obj: Any, value: str) -> None: ...

class CharField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> str: ...
    def __set__(self, obj: Any, value: str) -> None: ...

class IntegerField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> int: ...
    def __set__(self, obj: Any, value: int) -> None: ...

class BooleanField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> bool: ...
    def __set__(self, obj: Any, value: bool) -> None: ...

class DateTimeField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> Any: ...
    def __set__(self, obj: Any, value: Any) -> None: ...

class AutoField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> int: ...
    def __set__(self, obj: Any, value: int) -> None: ...

class JSONField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> dict[str, Any]: ...
    def __set__(self, obj: Any, value: dict[str, Any]) -> None: ...

class BinaryField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> bytes: ...
    def __set__(self, obj: Any, value: bytes) -> None: ...

class URLField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> str: ...
    def __set__(self, obj: Any, value: str) -> None: ...

class EmailField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> str: ...
    def __set__(self, obj: Any, value: str) -> None: ...

class PositiveIntegerField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> int: ...
    def __set__(self, obj: Any, value: int) -> None: ...

class SmallIntegerField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> int: ...
    def __set__(self, obj: Any, value: int) -> None: ...

class BigAutoField:
    def __get__(self, obj: Any, objtype: Any | None = None) -> int: ...
    def __set__(self, obj: Any, value: int) -> None: ...

class Model:
    objects: Manager[Any]
    pk: int
    id: int
    
    def save(self, *args, **kwargs: Any) -> None: ...
    def delete(self, *args, **kwargs: Any) -> tuple[int, dict[str, int]]: ...
    def refresh_from_db(self, *args, **kwargs: Any) -> None: ...
    def full_clean(self, *args, **kwargs: Any) -> None: ...