# Generated by Django 5.2.15 on 2026-06-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_finder_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='velocity',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
