# Generated by Django 5.2.15 on 2026-06-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_cooldown_minutes_campaign_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('draft', 'Draft')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daily_connection_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daily_follow_up_limit',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='linkedin_campaign',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='linkedin_username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='velocity',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
