# Generated by Django 5.2.15 on 2026-06-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_campaign_description_and_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="ghost_mode_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
