# Generated by Django 5.2.15 on 2026-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_siteconfig_bettercontact_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("connect", "Connect"),
                    ("check_pending", "Check Pending"),
                    ("follow_up", "Follow Up"),
                    ("send_manual_message", "Send Manual Message"),
                ],
                max_length=20,
            ),
        ),
    ]
