# Generated by Django 5.2.15 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_task_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]