# Generated by Django 5.2.15 on 2026-07-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_campaign_product_pitch_icp_followup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="follow_up_strategy",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="campaigntemplate",
            name="booking_link",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="campaigntemplate",
            name="follow_up_strategy",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="campaigntemplate",
            name="product_pitch",
            field=models.TextField(blank=True),
        ),
    ]
